//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meteo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pomiary
    {
        public int PomiarID { get; set; }
        public System.DateTime DataCzas { get; set; }
        public Nullable<double> PM1 { get; set; }
        public Nullable<double> PM25 { get; set; }
        public Nullable<double> PM10 { get; set; }
        public Nullable<double> Temperatura { get; set; }
        public Nullable<double> Wilgotnosc { get; set; }
    }
}
